dist: trusty
sudo: false
language: node_js
node_js:
- stable
addons:
  ssh_known_hosts:
  - 145.14.158.14
after_success:
- npm run report-coverage
before_install:
- openssl aes-256-cbc -K $encrypted_046d935b06c7_key -iv $encrypted_046d935b06c7_iv
  -in .travis/beaglBack.enc -out .travis/beaglBack -d
- npm i
- npm run test
- chmod 600 ./.travis/beaglBack
- ssh-add ./.travis/beaglBack
- ssh $SSH_HOST < ./.travis/deploy.sh
